name: 'Deploy to Sandbox'

on:
  push:
    branches: [sandbox]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Laravel Forge
    runs-on: ubuntu-latest

    if: github.event_name != 'pull_request'
    steps:
      - name: Deploy Develop Code
        uses: jbrooksuk/laravel-forge-action@v1.0.4
        with:
          trigger_url: ${{ secrets.SANDBOX_TRIGGER }}

  remove:
    name: Remove Sandbox Branch
    needs: [deploy]
    runs-on: ubuntu-latest

    if: github.event_name != 'pull_request'
    steps:
      - name: Delete Sandbox
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.VERAN }}
          branches: sandbox
