name: 'Develop Test and Deploy'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.1, 8.2]

    name: PHP ${{ matrix.os }} ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php zen key:generate

      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Build assets
        run: npm run prod

      - name: Execute tests
        run: php zen test

  deploy:
    name: Deploy to Laravel Forge
    needs: [tests]
    runs-on: ubuntu-latest

    if: github.event_name != 'pull_request'
    steps:
      - name: Deploy Develop Code
        uses: jbrooksuk/laravel-forge-action@v1.0.4
        with:
          trigger_url: ${{ secrets.SANDBOX_TRIGGER }}
